os:
  - linux
dist: trusty
sudo: false
language: node_js
node_js:
  - lts/*
matrix:
  include:
  - env: BUILD_ARCH=x64
    addons:
      apt:
        packages:
          - rpm
          - dpkg
          - fakeroot
          - libudev-dev
          - libxss1
          - libgtk2.0-0
          - libgconf-2-4
          - libnss3
          - libxtst6
          - libasound2
          - libusb-0.1-4
          - libusb-1.0-0
  - env: BUILD_ARCH=ia32
    addons:
      apt:
        packages:
          - rpm
          - dpkg
          - fakeroot
          - multiarch-support
          - libudev-dev:i386
          - libxss1:i386
          - libgtk2.0-0:i386
          - libgconf-2-4:i386
          - libnss3:i386
          - libxtst6:i386
          - libasound2:i386
          - libusb-0.1-4:i386
          - libusb-1.0-0:i386
          - gcc-multilib
          - g++-multilib
  allow_failures:
    - env: BUILD_ARCH=ia32
  fast_finish: true
cache:
  directories:
    - $HOME/.npm
    - $(npm config get prefix)/lib/node_modules
    - $(npm config get prefix)/bin/electron-forge
    - node_modules
install:
  - electron-forge --version || npm install -g electron-forge
  - npm install --ignore-scripts
  - node node_modules/electron-chromedriver/download-chromedriver.js
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm run lint
  - electron-forge make -a $BUILD_ARCH
  - npm run test
after_failure:
  - cat $HOME/recta-error.log
notifications:
  slack: recta-project:4FFGkXeZXIJdPYi3Xkp6i9YK
deploy:
  provider: releases
  api_key:
    secure: UXy9Qxc/tBB/3lhMASY34snXtmO/urwoF+zYAUcauFQtxLeJ5x0uqW+BfOffaJd1ZlknrvRzaBg55Sy+SUaq96QaPyBQHTx5zm/AFsv6/uub9fBOBOUHyKJOzh3f3FEfb+/YeqzCAlH3BvnK4RUOCyasg//XxgNqFg6lyRF/+LfKj803+xeoZNptompNa4GPiJhCXyNn5/DEQ/1xJdSq3r12hZh+YPE5scGCyXfxx0gAKfCnhpnHXSmQkmk8xlRkwkg3qVezvCrYgEl9VRt0lkTLGeqQea5/cOsyonSL/diemNsOuPHjJl6Y4oR7MgHh/hnm9AIn6I3ihazhCDNIX7G/FQnsukQoYcDVjJ83pd7/frk30LfLzpNAbJzHJZC1HvcS5pX4L8dcoEBknTv+miOIsLzIq5kIw7GA2wcQGX3FR9Ny/FOu58EX7CmZ8jpSNzJjF/CKkXT7vHsajnpANvfnvXOcyPZ0LbAtwAaDo/+VoUV4ShY2Tq4ue4omwm/io98A/Uh4EAO3teREtwuLL7Z2olxiRffHepmCRr2bqGsN+qWWAHwItpKAGiKo98XiyvfEOYOne/kOloe7aoj3VzrNzSQ4rGCmt5d/7ggUWIX2nLZPMrZtTHkWoF8jHMP3MphlPmcfKuSlEolifs96C574dR8UYB56jTu3JKPDKt8=
  file_glob: true
  file: out/make/*
  draft: true
  tag_name: $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
