os:
  - linux
dist: trusty
sudo: false
language: node_js
matrix:
  include:
  - node_js: lts/*
    env: BUILD_ARCH=ia32
    env: APT_ARCH=:i386
  - node_js: lts/*
    env: BUILD_ARCH=x64
    env: APT_ARCH=
cache:
  directories:
    - $HOME/.npm
    - node_modules
addons:
  apt:
    packages:
      - rpm
      - dpkg
      - fakeroot
      - libudev-dev$APT_ARCH
      - gcc-multilib
node_js:
  - lts/*
install:
  - npm install -g electron-forge
  - npm install
script:
  - npm run test
  - electron-forge make -a $BUILD_ARCH
