os:
  - linux
dist: trusty
sudo: required
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - $HOME/.npm
    - node_modules
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt install -y rpm dpkg fakeroot libudev-dev libudev-dev:i386 gcc-multilib g++-multilib
install:
  - npm install -g electron-forge
  - npm install
script:
  - npm run test
  - electron-forge make -a ia32,x64
