os:
  - linux
dist: trusty
sudo: false
language: node_js
node_js:
  - lts/*
matrix:
  include:
  - env: BUILD_ARCH=x64
    addons:
      chrome: stable
      apt:
        packages:
          - rpm
          - dpkg
          - fakeroot
          - libudev-dev
          - libxss1
          - libgtk2.0-0
          - libgconf-2-4
          - libnss3
  - env: BUILD_ARCH=ia32
    addons:
      chrome: stable
      apt:
        packages:
          - rpm
          - dpkg
          - fakeroot
          - libudev-dev:i386
          - libxss1:i386
          - libgtk2.0-0:i386
          - libgconf-2-4:i386
          - libnss3:i386
          - gcc-multilib
          - g++-multilib
cache:
  directories:
    - $HOME/.npm
    - node_modules
install:
  - npm install -g electron-forge
  - npm install --ignore-scripts
before_script:
  - "export DISPLAY=:99.0"
  - "export {no_proxy,NO_PROXY}="127.0.0.1,localhost""
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm run lint
  - electron-forge package -a $BUILD_ARCH
  - npm run test
notifications:
  email: false
